### ISSUE TITLE
[Bug]: Failure: could not clone https://github.com/zitadel/zitadel.git: signal: killed

### ISSUE THREAD

**Issue by khatiwada-Saurav** [zitadel/typescript#108]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

2.56.0 

### Describe the problem caused by this bug

When i try to pnpm generate it is giving me this error . i try to clean up the node modules and all but failed.

### To reproduce

just you have to pnpm generate 

### Screenshots

![Screenshot 2024-08-10 at 14 09 10](https://github.com/user-attachments/assets/ec46ab10-3441-400b-99f4-61b5b390338a)

### Expected behavior

it should have generate

**Comment by peintnermax** [comment]
> hm @peintnermax have you experienced this as well?
> 
> I tested it on my mac and did not see this problem 😓

No the error suggests that it is a local connection issue. Our builds work too, so it is not an issue for us.

**Comment by fforootd** [comment]
@khatiwada-Saurav does this error persist?

The git clone happens during the buf generate which loads the latest proto files from zitadel/zitadel

**Comment by hifabienne** [comment]
As we didn't get any response anymore, I will close the issue for now.
Feel free to reopen, if you can provide us with more informaiton
