### ISSUE TITLE
Login: Register Passkey

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#13]
As an enduser I want to be able to register my user with passkey authentication, so I don't have to remember my password

**Acceptance Criteria**
- [x] The user has a description link to read more about passkey what it is and why it is useful
- [x] I am able to choose the authentication method when registering my user
- [x] I am able to either send password or passkey registration
- [x] When choosing passkey registration the user doesn't need to give a name for the passkey
- [x] I am also able to register both password and passkey so that I have the password as a backup authentication method
- [x] After login the user should be asked if he want to register passkey directely
- [x] The user is able to directly add the passkey after the login, the user is asked do you want to add passkey for easier login next time

**Comment by peintnermax** [comment]
implementation done with https://github.com/zitadel/typescript/pull/29
