### ISSUE TITLE
Login: Register User with IDP

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#14]
As a developer I want to be able to register a user with idp through the default registration ui, so I don't have to build it myself.

**Acceptance Criteria**
- [x] Ui is implemented in the package and used by the login ui
- [x] I am able to send the org id or primary domain to the login ui
- [x] If an org id or primary domain is sent, organization idps are shown
- [x] If no org id or primary domain is sent, instance idps are shown
- [x] User clicks on idp and is redirected to the provider
- [x] After login in the provider user gets back to login
- [ ] When the user exists already in ZITADEL a success page is shown / or redirect to the application if no further steps needed
- [x] When the user doesn't exist, depending on the configuration the user will be created automatically or a register screen is shown or the user can choose to link with an existing user

**Comment by peintnermax** [comment]
`When the user exists already in ZITADEL a success page is shown / or redirect to the application if no further steps needed`

currently the error message is shown on the success page of the register. I think its the most generic way of handling this behaviour in an example app. Users can intercept the error there and do whatever they want.
