### ISSUE TITLE
Test Different Scenarios

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#161]
## General
- [ ] The login feels pretty slow, i do see some screens sometimes, which then are skiped because some informations already exist, e.g login hint, first to second screen
- [x] Error messages are not human readable, its always a server error

## Bugs
- [x] Redirect to app doesn't work after user registration
<img width="460" alt="image" src="https://github.com/user-attachments/assets/9d4b1437-9061-45cc-aa4e-1aec45282b21">

- [x] Reset Password click results in error
<img width="460" alt="image" src="https://github.com/user-attachments/assets/758cd9eb-3554-46ea-a507-30b3f6770ab3">

- [x] When redirecting to the login with an org scope, and entering a user from the wrong organization, I get an error message which doesn't help me anything
<img width="484" alt="image" src="https://github.com/user-attachments/assets/988587ce-f19e-427f-9ebe-6e7d49ec3dda">

- [x] When a error occures, I can't do anything afterwards, continue button loads, and back doesn't work
<img width="693" alt="image" src="https://github.com/user-attachments/assets/fc480bc4-393f-4875-93de-5278509325a0">

- [x] When sending a org scope and clicking on register new user, i loose the context of the org and be on the default org again
- [x] If i have enforced mfa, i can skip it and login without mfa
- [x] MFA setup doesn't show what i have configured on my organization, it always shows passkey
- [x] if password hide is enabled, password reset is still shown on the password screen
- [x] if "ignore unknown username" is enabled, i still get an error if the username could not be found
- [ ] Per default the settings of the default organization should be triggered and not the instance settings

## Improvements
- [x] After registering a new user with username password I want to be authenticated directly, so i don't have to reenter username password again
- [ ] If username password needs to entered again, I want the loginname to be prefilled
- [ ] when i redirect to the login, and get the username screen, i have a back button, which doesn't make anything, I think the back button is useless in that case or should redirect back to the app
- [ ] Should error message differ when user is locked? I always get password could not be verified
- [ ] Default behaviour is not always the same, sometimes i am per default on the username screen and sometimes on the select account screen

**Comment by hifabienne** [comment]
- Register User with Username Password
- Register User with Passkey
- Register User with External IPD

**Comment by peintnermax** [comment]
"If i have enforced mfa, i can skip it and login without mfa" and
"MFA setup doesn't show what i have configured on my organization, it always shows passkey"
I guess you ment the prompt to setup passkeys. this shows up, when passkeys are enabled in the login settings. I have changed the priority to setup MFA before hinting to setup passkeys now.

**Comment by peintnermax** [comment]
"Per default the settings of the default organization should be triggered and not the instance settings"
 this can be implemented after: https://github.com/zitadel/zitadel/issues/8616

**Comment by hifabienne** [comment]
@peintnermax should we close this issue for now as i did a new test?
#199

**Comment by hifabienne** [comment]
i close it for now, let me know if we need to reopen
