### ISSUE TITLE
Login: Handle invite user flow

### ISSUE THREAD

**Issue by livio-a** [zitadel/typescript#166]
https://github.com/zitadel/zitadel/issues/8310 added the possibility to create an invitation link for a user to create their first authentication method.

The V2 login need to be able to handled that and allow user to setup password, passkey and an IdP.

### Acceptance criteria
- [x] An invitation link to the login UI is handled and verifies the provided code using the User V2 VerifyInviteCode endpoint
- [x] The user has the possibility to resend the code to their email (User V2 ResendInviteCode)
- [x] After successful verification, the user is presented the available options for authentication (password, passkey, IdP(s))
   - [x] Available options are based on the settings of the organization of the user
- [ ] Please test the following usecases:
   - [x] Given user is created with firstname, lastname, email, email not verified, the user will get an invite code and can add a password, user email is verified and password set
   - [x] Given user is created with firstname, lastname, email, email not verified, the user will get an invite code and can add a passworkey, user email is verified and passkey set
   - [x] Given user is created with firstname, lastname, email, email not verified, the user will get an invite code and can add sso, user email is verified and sso linked

**Comment by hifabienne** [comment]
@peintnermax can you please estimate this issue?

**Comment by livio-a** [comment]
We should also have a look at how to handle if the code is expired when clicking the link:
https://github.com/zitadel/zitadel/issues/8850
