### ISSUE TITLE
OIDC: Proxy

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#48]
The new login should implement the OIDC Standard.

## Acceptance Criteria
- [x] PKCE flow with Authorization Code is implemented
- [x] Login hint is implemented and does fill the user automatically and if needed sent to the next screen
- [x] I am able to send the following prompts, based on the prompt the corresponding screen is shown:
   - [x] login
   - [x] select_account
   - [x] create
   - [x] none
- [x] At the end of the flow, I am redirected to the sent callback url
- [x] Guide about oidc flow in new login is updated: https://zitadel.com/docs/guides/integrate/login-ui/oidc-standard

**Comment by hifabienne** [comment]
@peintnermax please estimate

**Comment by peintnermax** [comment]
https://github.com/zitadel/zitadel/pull/7378 describes the progress of the oidc standard in the new login
