### ISSUE TITLE
Guide How to setup vercel and deploy to vercel button

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#50]
As an end user I want to be able to deploy the login to vercel easy and know what I have to do to link it to my instance.

## Acceptance Criteria
- [x] Deploy to vercel button, redirect user to vercel and deploys login directly
- [x] Guide in our zitadel docs How to deploy login to vercel
  - [x] What env vars do I need
  - [x] Supported flows, scopes
  - [x] Supported authentication methods
  - [x] Supported additional features (e.g, domain discovery, ...) 
- [x] Architectural Overview of login and console and how they work together
   - [x] Domains for login and consol, etc
- [x] Link to guide in readme

**Comment by peintnermax** [comment]
this PR improves the docs of the new typescript-repo  https://github.com/zitadel/zitadel/pull/7621
