### ISSUE TITLE
New Login UI: Current state?

### ISSUE THREAD

**Issue by kbumsik** [zitadel/typescript#55]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I have been watching [the new login UI](https://github.com/zitadel/typescript/tree/main/apps/login) since last year because, as a company who is using Next.js and is looking for a Keycloak alternative which allows us fully customize UI, this will be a really great starting point to fully customize UI.

But looking at the commit logs and related issues, unfortunately the development of the new login UI seems to be stale.

Cloud you please tell us the current state of the new login UI?

### Describe your ideal solution

Provide a current state of the new login UI, such as road map or ETA.

### Environment

ZITADEL Cloud

**Comment by fforootd** [comment]
Hey, sorry for my late reply, this slipped past me.

We already implemented some of the components we need and there is definitely work ahead of us.

Let us add something that shows the progress of this repository and what you can already use.

CC @peintnermax

**Comment by hifabienne** [comment]
We have now added a list of features to the readme of the repository:
https://github.com/zitadel/typescript?tab=readme-ov-file#login

The goal currently is to have a running login with minimal features such as oidc flow and password login, ready by the end of the current quarter/beginning of the next quarter.
And next quarter we will work on adding more features such as idps, mfa, etc.

I will close the issue for now, as we have added the state to the readme

**Comment by kbumsik** [comment]
Thanks for the detailed info!

> We have now added a list of features to the readme of the repository:
https://github.com/zitadel/typescript?tab=readme-ov-file#login

Great, this feature list is really useful to figure out the current state.

I look forward to see improvements this year!
