### ISSUE TITLE
[Bug]: Type Error 

### ISSUE THREAD

**Issue by khatiwada-Saurav** [zitadel/typescript#77]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

2.56.0 

### Describe the problem caused by this bug

@zitadel/server:build: src/proto/server/zitadel/admin.ts(31561,62): error TS2345: Argument of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/org").Domain' is not assignable to parameter of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/instance").Domain'.
@zitadel/server:build:   Type 'Domain' is missing the following properties from type 'Domain': domain, primary, generated
@zitadel/server:build: 
@zitadel/server:build: Error: error occured in dts build
@zitadel/server:build:     at Worker.<anonymous> (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/tsup@8.1.0_typescript@5.5.3/node_modules/tsup/dist/index.js:2693:26)
@zitadel/server:build:     at Worker.emit (node:events:520:28)
@zitadel/server:build:     at MessagePort.<anonymous> (node:internal/worker:271:53)
@zitadel/server:build:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
@zitadel/server:build:     at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
@zitadel/server:build: DTS Build error
@zitadel/server:build: RollupError: [plugin dts] src/proto/server/zitadel/admin.ts: Failed to compile. Check the logs above.
@zitadel/server:build:     at getRollupError (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/shared/parseAst.js:282:41)
@zitadel/server:build:     at Object.error (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/shared/parseAst.js:278:42)
@zitadel/server:build:     at Object.error (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/shared/rollup.js:804:32)
@zitadel/server:build:     at Object.error (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/shared/rollup.js:19790:42)
@zitadel/server:build:     at generateDtsFromTs (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/tsup@8.1.0_typescript@5.5.3/node_modules/tsup/dist/rollup.js:7776:22)
@zitadel/server:build:     at /Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/tsup@8.1.0_typescript@5.5.3/node_modules/tsup/dist/rollup.js:7783:59
@zitadel/server:build:     at _nullishCoalesce (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/tsup@8.1.0_typescript@5.5.3/node_modules/tsup/dist/rollup.js:1:198)
@zitadel/server:build:     at Object.transform (/Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/tsup@8.1.0_typescript@5.5.3/node_modules/tsup/dist/rollup.js:7783:18)
@zitadel/server:build:     at /Users/saurav/Documents/Kepler/zitadel-console/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/shared/rollup.js:989:40
@zitadel/server:build: src/proto/server/zitadel/management.ts(14732,67): error TS2345: Argument of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/member").SearchQuery' is not assignable to parameter of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/user").SearchQuery'.
@zitadel/server:build:   Types of property 'emailQuery' are incompatible.
@zitadel/server:build:     Type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/member").EmailQuery | undefined' is not assignable to type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/user").EmailQuery | undefined'.
@zitadel/server:build:       Property 'emailAddress' is missing in type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/member").EmailQuery' but required in type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/user").EmailQuery'.
@zitadel/server:build: src/proto/server/zitadel/management.ts(18711,67): error TS2345: Argument of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/member").SearchQuery' is not assignable to parameter of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/user").SearchQuery'.
@zitadel/server:build: src/proto/server/zitadel/management.ts(24338,67): error TS2345: Argument of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/member").SearchQuery' is not assignable to parameter of type 'import("/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server/src/proto/server/zitadel/user").SearchQuery'.
@zitadel/server:build: 
@zitadel/server:build:  ELIFECYCLE  Command failed with exit code 1.
@zitadel/server:build: ERROR: command finished with error: command (/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server) /opt/homebrew/bin/pnpm run build exited (1)
@zitadel/server#build: command (/Users/saurav/Documents/Kepler/zitadel-console/packages/zitadel-server) /opt/homebrew/bin/pnpm run build exited (1)

### To reproduce

pnpm generate and pnpm build 

### Screenshots

![Screenshot 2024-07-11 at 14 44 42](https://github.com/zitadel/typescript/assets/139867782/d1ff2fb7-ee9c-4a5f-a889-d3931884daeb)

### Expected behavior

it should build normally

**Comment by peintnermax** [comment]
`@zitadel/server` packages is replaced with `/node` and `/client` package now
