### ISSUE TITLE
[Bug]: "id_token_hint invalid" while logging out with id_token not being expired

### ISSUE THREAD

**Issue by khatiwada-Saurav** [zitadel/typescript#79]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

2.51.0 

### Describe the problem caused by this bug

I want to logout using  id_token_hint  but it is giving me an error saying 
"error": "invalid_request",
"error_description": "id_token_hint invalid"

I have checked the Id token before request and it has not expired.

### To reproduce

try to logout using id_token_hint 

oidc/v1/end_session (EndPoint)

**Comment by livio-a** [comment]
Can you give us some more details on your request, e.g. your id_token or a HAR file

**Comment by khatiwada-Saurav** [comment]
i solved this using client id and manually deleting session and removing from the cookie
